# Generated by Django 5.1.3 on 2024-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='final_cost',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
